baseURL: 'https://next.worldofsteelcraft.tk/'
languageCode: en-us
title: World of SteelCraft Beta
theme: WoSCWebTheme
params:
  description: World of SteelCraft is a server owned by Scary Master Playz which is currently managed by himself and other admins. We're welcoming Filipino Minecraft Players to join

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false