baseURL: 'https://worldofsteelcraft.tk/'
languageCode: en-us
title: World of SteelCraft
theme: WoSCWebCore
params:
  description: World of SteelCraft is a server owned by Scary Master Playz which is currently managed by himself and other admins. We're welcoming Filipino Minecraft Players to join
  pagePreviewImage: /images/preview.png
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
disqusShortName: worldofsteelcraft

markup:
  goldmark:
    renderer:
      unsafe: true
